---

- name: fetch-client-name-from-server
  ansible.builtin.fetch:
    src: "/chef/resources/users/{{ chef_client_name}}.pem"
    dest: "/tmp/{{ chef_client_name }}.pem"
    flat: true
  delegate_to: "{{ chef_server_host }}"
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: /Users/chalkan/.ssh/id_rsa 

- name: fetch-organization-pem-from-server
  ansible.builtin.fetch:
    src: "/chef/resources/organizations/{{ chef_organization_name }}.pem"
    dest: "/tmp/{{ chef_organization_name }}.pem"
    flat: true
  delegate_to: "{{ chef_server_host }}"
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: /Users/chalkan/.ssh/id_rsa

