---
- name: create-chef-resources-folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: 
  - /chef
  - /chef/resources
  - /chef/resources/users
  - /chef/resources/organizations
    
